[[XDiag]]
arch = "aarch64"
git-tree-sha1 = "7414df85deefc282fcced2b67d7f028a830994b9"
julia_version = "1.10.0"
os = "macos"

    [[XDiag.download]]
    sha256 = "0dc31eacecb16775839cbd77b534ba721441d7efcb35201c8f614297bd8a408e"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "aarch64"
git-tree-sha1 = "c287052756cec26e7305cb059cd9a8d19004846a"
julia_version = "1.11.1"
os = "macos"

    [[XDiag.download]]
    sha256 = "49947a843aea3097815cda3fdc62c1e7a01bfbe642f3d4a77dccfba39b4e2b3a"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.aarch64-apple-darwin-julia_version+1.11.1.tar.gz"
[[XDiag]]
arch = "aarch64"
git-tree-sha1 = "a1ccdb9951cb91ea25f8af207609c01c132ee746"
julia_version = "1.7.0"
os = "macos"

    [[XDiag.download]]
    sha256 = "7fbeec326c1abcf6d5f7ae195947607950e1ff82bc5a06094ff0409673bdde8d"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[XDiag]]
arch = "aarch64"
git-tree-sha1 = "f38d5c5f84b7a327d187c5211fa568e0c22ef765"
julia_version = "1.8.2"
os = "macos"

    [[XDiag.download]]
    sha256 = "f156c9b3325ed9ec6d35374c9490dabd782cc8ad2874e4cafbe6b04083cfb336"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.aarch64-apple-darwin-julia_version+1.8.2.tar.gz"
[[XDiag]]
arch = "aarch64"
git-tree-sha1 = "cd13341314033fbb045018508398982050aeb9ef"
julia_version = "1.9.0"
os = "macos"

    [[XDiag.download]]
    sha256 = "7f55127be3f17119226074b09edc9fb6907cf36b04b2595df4155299358b4965"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05bae4be81f2fb912e0cabbbfe78b25eedff79e0"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "62995e16d1d0e54f370f7a37b515d89eb0a734db3548bc6a94df697770adcf5f"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.aarch64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "020d295036c2d2d012ff2a15b3230561a40f4152"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "58b873e1c5d65c5bb2c61e98e5ce34d9fec191b704ca47c39ec9f2a55cb03a13"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.aarch64-linux-gnu-cxx03-julia_version+1.11.1.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d5a6cadf466be83125df8ef873bcbdf5c63fafd8"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "4e427a414eb3ccec930c256259e6290f7b2e115f620936dfefe41f05711740a4"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.aarch64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "343c061e862a2bdc7e8ee14cbb10fd2a9a5a4b3e"
julia_version = "1.8.2"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "09ac5e506e36c3378971ebc5a11bbe9b8316f63ede4fa9254744a33af6bd8c93"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.aarch64-linux-gnu-cxx03-julia_version+1.8.2.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c622812f4369e515c0891fcd4d2dc9b399456f76"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "05a443e324257a25ab2a095b6a9aa5387ea4de37043c8bd93658bb6cff24dc93"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.aarch64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d67f16549263e54de17d0d0fa4c2322ffe291330"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "d0d8d5892ac81e1e5c80c7fbbdd0e2db1e5611eda36b63a1f9662ea803cac8fc"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "49dce5a80746b6efa569a3e5b968c4d7e10a9039"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "ac6c84f21468874b8816b149cb8ebb9e039d0bea0e6ea63aad715bd0bb0d4f9a"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.aarch64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc2fa9fbfa6b7e61f9b1d72fa13b0cfa83e692fd"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "d535c9da3cdbcc15381ecfddc0683cf7edf850c6ca6db1cedaf504bbf0e58f3a"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.aarch64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "137275a92661b417fbc776e72669bc8ab65e32c1"
julia_version = "1.8.2"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "74ae0c12eebf5f88d280df96b868db1cb5cc2e09f0f690709ae0fbf46f7f8992"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.aarch64-linux-gnu-cxx11-julia_version+1.8.2.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5321f28be214e5937fdf332f533c9b7ac8eefa41"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "66ade15ea2656d6239a9c64ef1a3eb606aed2330f8f6ce836e0eb1523887d2f8"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.aarch64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[XDiag]]
arch = "x86_64"
git-tree-sha1 = "d15fe85409e5c717f4989ec07d839935984d0afc"
julia_version = "1.10.0"
os = "macos"

    [[XDiag.download]]
    sha256 = "7e230deb644180df94e6f1d8d4a9ffa605f9648c5a5c69edd8630c9c4366fd7d"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "x86_64"
git-tree-sha1 = "46e7c951ef49aa4820786c08940cf0babb59d839"
julia_version = "1.11.1"
os = "macos"

    [[XDiag.download]]
    sha256 = "aa1c649b7b18a34317f5c0f746e029e1d23bbeb90a41178d67fc8a75502f5c1b"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-apple-darwin-julia_version+1.11.1.tar.gz"
[[XDiag]]
arch = "x86_64"
git-tree-sha1 = "25af2644c2cadf9fada45dd294e180484efd602c"
julia_version = "1.7.0"
os = "macos"

    [[XDiag.download]]
    sha256 = "ff1b48e66cde2763bd590e38b01dd8740b532425980d36c2ae5a1670c1b55d90"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[XDiag]]
arch = "x86_64"
git-tree-sha1 = "6727ba22d106cf20928cc57791a0731b6a99fb7b"
julia_version = "1.8.2"
os = "macos"

    [[XDiag.download]]
    sha256 = "4576d2d239ff22ed54a5ef1b23035a436287c55a503278ca94eaad126be5b44f"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-apple-darwin-julia_version+1.8.2.tar.gz"
[[XDiag]]
arch = "x86_64"
git-tree-sha1 = "3dbf1846706ae4cd2b4cf9c371d0a7fca8f56634"
julia_version = "1.9.0"
os = "macos"

    [[XDiag.download]]
    sha256 = "7721f59e8bc9bedaa7ccfb400eb66ef24f60a79a9e57e07a33c720352215cd55"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-apple-darwin-julia_version+1.9.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "805080938f5dcbd9d74d5330bfdb31e71dbf18a0"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "1423cc5dc0d22632df2ed1bd1fbf84ae724ecdb1949c88fd84d6ec2672f6d328"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9b6367a1595589bffef6fdd9c1e4a3e8cff7d3dc"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "d513c2aa4224cad544bda04d8dcd7e05497225830e9f5594463edbe9aed6e07e"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-linux-gnu-cxx03-julia_version+1.11.1.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe3213abce832cfca18425c483f7b07bc6ed62f6"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "1d1d8f5f78d78116f035f28c95205ca799617cbc32360fd2944d59e43e6232c3"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3814fef65faa1c6214fc3820456022f2d67c67e1"
julia_version = "1.8.2"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "8edd71de9f426380f2bfb21b11bfa52cc7c651d2e60800fd13e28d8b6f80c280"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-linux-gnu-cxx03-julia_version+1.8.2.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9350d9d92a3b5e9a4aac8cf16508e9755caeb056"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "c49cf2a0b4bb65a00c3a7e1cc6f950c81a90fba1dfa8744004f78551eeddc041"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0f4aff557c34737ec4c686de6200bc560f36d38"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "ebc77e04e7b1a53fc7cdaaec70d52b0baf4da7603d8ba8f1c6a560e6897b530a"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf9918b1e778278eb97ac76fa588333e65f4a129"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "04250a179ca55f691249064e14566e4d1a57f3f3a962776b39500756e9c92437"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "703e53c95079b0ccf7a96747f71a1ed8d9084a9c"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "5d6af89f0d6ec9dd8536927a3b977028cae831e44dff9974f86b6985bf79cf9a"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fea8a68ae76c34f6880dbd29f57d88a6a3cfa83f"
julia_version = "1.8.2"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "0db4c5143b222ac454390ac64f1efdb25943ee01bff5e79b8215e52c6b5cc15b"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-linux-gnu-cxx11-julia_version+1.8.2.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a0af38f888f6698201826b5038b71fdeeaad761"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "4e4214566157c44d0c066bae50bd1c29de4755e10ede4399436fbd989839ef5a"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4936793fd2d6b5207cdb2300c7898f4953776d40"
julia_version = "1.10.0"
os = "windows"

    [[XDiag.download]]
    sha256 = "eb2739caffef4a5fc1ab02f53530de0ace5e68d80153ad1e1ead92b46c00877f"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-w64-mingw32-cxx03-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e36495019b3fea127bd393f17c21a06587a2d8d0"
julia_version = "1.11.1"
os = "windows"

    [[XDiag.download]]
    sha256 = "e6dd286404567f20d9a4ee97a10db95ac272a7d62455c190de9c00247ecec5a5"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-w64-mingw32-cxx03-julia_version+1.11.1.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f816df455c984b710f05f7d289a02e31840bd72b"
julia_version = "1.7.0"
os = "windows"

    [[XDiag.download]]
    sha256 = "2a603bedf33a6a6b161d1d4ecc5158d6e07fcab4e69616d0e129586980baf5fe"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-w64-mingw32-cxx03-julia_version+1.7.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "266127c90c51ad57781b303a8a370fac475067da"
julia_version = "1.8.2"
os = "windows"

    [[XDiag.download]]
    sha256 = "b775b27421b6f02e72c2baab38931f915d5f83ef48527daa84917c54b72b8237"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-w64-mingw32-cxx03-julia_version+1.8.2.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9b3fc9fbe422878250f1c174ce41481b4c129a49"
julia_version = "1.9.0"
os = "windows"

    [[XDiag.download]]
    sha256 = "26928b4ab36e7a3fc538f6977c67933e9d412f7123d0e76d1b68c602161cf540"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-w64-mingw32-cxx03-julia_version+1.9.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b8c8acaa52eb1a5984f0cef8a1546f3f5fcbacd"
julia_version = "1.10.0"
os = "windows"

    [[XDiag.download]]
    sha256 = "7f29ed6bab0d21246689024864316c36c92ca570387397bddc5c19c13b4e19ab"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4bb82bcc8a12cf0ed07d211804a485d2d2938c48"
julia_version = "1.11.1"
os = "windows"

    [[XDiag.download]]
    sha256 = "a7c408d354ca3c6e8d339e2111d55b32c2818b66d0f149d769c437c5c6711d13"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-w64-mingw32-cxx11-julia_version+1.11.1.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4878530f6f81891d6f30e016e5777aedbdf17400"
julia_version = "1.7.0"
os = "windows"

    [[XDiag.download]]
    sha256 = "422101fbc91c5fdaa4f7d96368684077f7b66849f9aeeb23516d2219c93dde3a"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-w64-mingw32-cxx11-julia_version+1.7.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e3bca7289470280b45fe95c8eb17b5b719cf3f7"
julia_version = "1.8.2"
os = "windows"

    [[XDiag.download]]
    sha256 = "57628c45f5c0c8123851d61867673ab96aa36f237ecd6045557f82f7d5216d95"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-w64-mingw32-cxx11-julia_version+1.8.2.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ceb5f953c73318a56c2df2b8d0e6ebf07bed6225"
julia_version = "1.9.0"
os = "windows"

    [[XDiag.download]]
    sha256 = "5b921009d15ae13314217c9c6927ba7692b45b1d97c7584db9a5177b9209f908"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.3.2+0/XDiag.v0.3.2.x86_64-w64-mingw32-cxx11-julia_version+1.9.0.tar.gz"
