[[XDiag]]
arch = "aarch64"
git-tree-sha1 = "1702132eb5abce7ce928dbce268ddbd85c466906"
julia_version = "1.10.0"
os = "macos"

    [[XDiag.download]]
    sha256 = "7a7fc98a4e8247b5f8ac4c65546ff5bf19b3f47b13e4d98257d9c950989fd936"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "aarch64"
git-tree-sha1 = "1153b0bc42a6b253b1284934dbd63f40af781909"
julia_version = "1.11.0"
os = "macos"

    [[XDiag.download]]
    sha256 = "a33e33a537a744673e434d0c72341548db1475137fcb653f48be5f511a1f8e02"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.aarch64-apple-darwin-julia_version+1.11.0.tar.gz"
[[XDiag]]
arch = "aarch64"
git-tree-sha1 = "d8229a557ba87f7be408ca3067c10bc993de50d8"
julia_version = "1.7.0"
os = "macos"

    [[XDiag.download]]
    sha256 = "79a503c3c09c33a71cf200eda91d80a655c73dc593720890a7412556a7cff986"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.aarch64-apple-darwin-julia_version+1.7.0.tar.gz"
[[XDiag]]
arch = "aarch64"
git-tree-sha1 = "ea05c3e465fc582e48c17cec4d62c25918be3fcf"
julia_version = "1.8.2"
os = "macos"

    [[XDiag.download]]
    sha256 = "d9e9c7d9f25fd23cfb2f1a12cd6241d49fdf9d7f707484de471535352b3d6547"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.aarch64-apple-darwin-julia_version+1.8.2.tar.gz"
[[XDiag]]
arch = "aarch64"
git-tree-sha1 = "af40d773b672f9295ab961cd6c407ea60cc2854a"
julia_version = "1.9.0"
os = "macos"

    [[XDiag.download]]
    sha256 = "9242cc6ad19eccf43ab3959405be2981f967798d137bfdb403b935a24e1592fa"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.aarch64-apple-darwin-julia_version+1.9.0.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d55f1b76c5a43892f9e8531bfa095ca519296c63"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "e4fcfcc189e49737cd363ccb37dfbc4e996fc530655c15a2e7f4ee3d279d0f32"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.aarch64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c073e2b834d94d8dc98daea7f076d05401f2b1ec"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "11b8af4d336381f66b21e6a6d2dae7328945a9091c2150b56094a5e1636d70b6"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.aarch64-linux-gnu-cxx03-julia_version+1.11.0.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d6e5853dcd64bfe41de66098e6d85366347aaf2"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "9184abb3cc23befa3b8d812ad5696a5e23ba377e368e302d5472c0409fda84c3"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.aarch64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a4bb2b6dd96dc9b9f4ba09cd75d139f1484d7070"
julia_version = "1.8.2"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "7ab1d51f92fc79359668a599c9ff126eaef7cac1eb8627d4bce831ff37cae4f0"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.aarch64-linux-gnu-cxx03-julia_version+1.8.2.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e58f1f45e8f76ed210a9b89d752c5eb472017f3"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "e1c6e44912546b945a88ba203ec851a94981027c9e519302fdfe1118ece1a513"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.aarch64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "506ad51b61048ccd139310400f1cc805fc690e62"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "1795087378d92e5bcdbfa059e88529c38217e1c7ef6f1ef24f74348d568abe3e"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89ae01b4ba42dd965db82dc380fb37a9188cf86a"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "22bd7fb818ecbaaf31bb1f15fdcdd867998881d8519a4ab0af457bf94a8271ed"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.aarch64-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1cae0159bb452fcf46b24ca2c4c092d6cf769e7"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "beec544e3d5d46e098c95eb1e5a7db0753514df6f7c3a99392e2fd70f4919066"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.aarch64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff3e2cf351534ab0a8bb4f99d41500367dd9437c"
julia_version = "1.8.2"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "aadb7337b1a6e7a13113021bb60980b3f57ad3ded1205e76e870e536d1d1d59e"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.aarch64-linux-gnu-cxx11-julia_version+1.8.2.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a03015c272b58e181ebfb0fd727e2f61a2abffb"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "d6ab300a11aa60ad0f359112bd62a3a83e249ac880acf9f17b3e9b99eb7e32ec"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.aarch64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[XDiag]]
arch = "x86_64"
git-tree-sha1 = "52b58dbc26d3257e9e2dcf186595361f19ff6653"
julia_version = "1.10.0"
os = "macos"

    [[XDiag.download]]
    sha256 = "0b1cafa611ff0954330482c5808165f5fb5521f82caff86f0cd31bce092dab8b"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "x86_64"
git-tree-sha1 = "23fe1b1d214b67d42dcdd8530e8ee8b0454a4ef3"
julia_version = "1.11.0"
os = "macos"

    [[XDiag.download]]
    sha256 = "8042c451938c8b4f4f1a89bd13410ebc696d48c8586ef02eeca67a0d23efc66d"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-apple-darwin-julia_version+1.11.0.tar.gz"
[[XDiag]]
arch = "x86_64"
git-tree-sha1 = "62970879e919a18b7149d537d305adabd9c926b2"
julia_version = "1.7.0"
os = "macos"

    [[XDiag.download]]
    sha256 = "4394e626db887d74b88bc86fb2800fdc593c05f0ba8549d3e622ed113d5f51e3"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-apple-darwin-julia_version+1.7.0.tar.gz"
[[XDiag]]
arch = "x86_64"
git-tree-sha1 = "3d7c268c747864470618304895951380447cf0c7"
julia_version = "1.8.2"
os = "macos"

    [[XDiag.download]]
    sha256 = "e30b112147d32ae9f6cf45107ce3b4f1e668cd248de7a4f47cbbf8695fd084e9"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-apple-darwin-julia_version+1.8.2.tar.gz"
[[XDiag]]
arch = "x86_64"
git-tree-sha1 = "7e260106f521b53c0e018f042d51f713fd38f64a"
julia_version = "1.9.0"
os = "macos"

    [[XDiag.download]]
    sha256 = "ef079df7c24145f6649c29faf24cfcd8ab7dc435fe7f51e22d68b31eb04e818d"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-apple-darwin-julia_version+1.9.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74fe2fb633ce219480805714490b878509267369"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "c696f86efc9612ef743eb569b93a6739ab3076c61fe38fccb2ec1acd8f363238"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-linux-gnu-cxx03-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d6d34df4c406ae2102b696d369bf4fd1d6ae77dd"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "26c11a9006a4e69eda3a8310c80003f4858c0f8dfb7d7f24c8679097d978eb80"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-linux-gnu-cxx03-julia_version+1.11.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ad402c51061222a07aa5d02a4e04b514d4ad65a"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "b4a6df3e50211df358b56e27003fa56888ab5edbfdaad6b521f57ecfa9bd3464"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-linux-gnu-cxx03-julia_version+1.7.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7fcbfdc3ef94d66f35daa1d6707d7790123c2456"
julia_version = "1.8.2"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "f860b912fab1b7933c64bf1c7a0f7686a19b56f3ea6c14545990a4c204cd210b"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-linux-gnu-cxx03-julia_version+1.8.2.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab61eba59a8aea89d4356894cbdf60c287b1f527"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "50f8a74d89ad3074fde85d9f81ed4cc47e741edcd35c8851ce9c6c813ec32361"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-linux-gnu-cxx03-julia_version+1.9.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2b9b467b4c819a8523680299e3ba7c0238e8ee8"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "9ae3ebf1c0ba0f0a620c16577e4f48c9bee754e2bc86c07d975171efe2823ddd"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13ee0e0f2688c928f951a5901dd0323829edfb02"
julia_version = "1.11.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "4e5719ef6245030aed8385739b09549abe2e47071f527fe6445b92ef2b859ecf"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-linux-gnu-cxx11-julia_version+1.11.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b1bbcb7a8d072f051f8354ecca08d7982d265b3"
julia_version = "1.7.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "e4e287d56ed36a7eb3bd5f431be3c7ce6fffcdcb34334b4df66a8c5cc94b4c2a"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-linux-gnu-cxx11-julia_version+1.7.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "214b0130beda9f4a317e70c113a103d67047fb10"
julia_version = "1.8.2"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "0642786fe77665f3f64ac83e3d6aa1c70f149c2bdaddb92dfdd60e93e6ddb05b"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-linux-gnu-cxx11-julia_version+1.8.2.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46902dcdd9cd201c591de3bc17aaa48d0151b2d5"
julia_version = "1.9.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "0023d9307b45bb1b5f10f8b2506fad2708e4650a3cef1f7eb30103d142f9fe47"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-linux-gnu-cxx11-julia_version+1.9.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5c2f666d9071d37da8234c8e0b0d8845fc18def2"
julia_version = "1.10.0"
os = "windows"

    [[XDiag.download]]
    sha256 = "1e246337987b45bc1aa2dc301e9cee3c6c250d304869188aa2b0cf37c5d5bd2f"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-w64-mingw32-cxx03-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20e6f84c3057ff2182d94f65c5b3c11b6f6e9ca3"
julia_version = "1.11.0"
os = "windows"

    [[XDiag.download]]
    sha256 = "af48b998126aab8bfcd683dc436092225d101f9b51609cff187f2872ce2d4321"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-w64-mingw32-cxx03-julia_version+1.11.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fb698bf2bfa3d0f25f066feaec95486ec7b58743"
julia_version = "1.7.0"
os = "windows"

    [[XDiag.download]]
    sha256 = "fa7defbb819438fe56ed67b38742738dfa922670f11e5e5d4ed7bcd7ea8e9b51"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-w64-mingw32-cxx03-julia_version+1.7.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0bad7d0a5f6d565f41bd6e2739d92df2bb73b27d"
julia_version = "1.8.2"
os = "windows"

    [[XDiag.download]]
    sha256 = "6802758e3dc6d88ff279719378d6aa2bc84a105850ed4272cda5825894cec4bd"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-w64-mingw32-cxx03-julia_version+1.8.2.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5393364c30af308ba73898469604ecea0935bf9d"
julia_version = "1.9.0"
os = "windows"

    [[XDiag.download]]
    sha256 = "94f0ebda1a779b46444ad9bee445d89250e80966568da37a4567c1854d95e8d6"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-w64-mingw32-cxx03-julia_version+1.9.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4834ef03e2aee909085dc68cc8a7b5f46f7ea9da"
julia_version = "1.10.0"
os = "windows"

    [[XDiag.download]]
    sha256 = "6664e81131777ed60957d07ef1e92798ed6083eb53406660fc0c3808bbb1984c"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7da31c2b13fdfd7944fcf702d2a9f7d0b19e0cbc"
julia_version = "1.11.0"
os = "windows"

    [[XDiag.download]]
    sha256 = "aa5f5db6f61d63e4842bdecd83d847e602aa9788d0177b65a995b62e7ce8cab6"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-w64-mingw32-cxx11-julia_version+1.11.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67e2ee5e60231c8b7b643030c418920aefa2203f"
julia_version = "1.7.0"
os = "windows"

    [[XDiag.download]]
    sha256 = "c77ec5dac6b5a8a2c578159a99096181c4b76687533e9315d8343e6e446f1e7c"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-w64-mingw32-cxx11-julia_version+1.7.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f49b57b9a427a31ec8e5fd4643a4f7c131ad782"
julia_version = "1.8.2"
os = "windows"

    [[XDiag.download]]
    sha256 = "fdaacd86b4b569994e73fb18d929b8d198eeb9ded934314829279018868c281e"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-w64-mingw32-cxx11-julia_version+1.8.2.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a912821e59da5297304d621fbf679bed77716edc"
julia_version = "1.9.0"
os = "windows"

    [[XDiag.download]]
    sha256 = "bf4293cb66fdb8da82e396773cc43cf84748dbbb9c7c0a2131158d7c95bf0db1"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.2.2+0/XDiag.v0.2.2.x86_64-w64-mingw32-cxx11-julia_version+1.9.0.tar.gz"
