[[XDiag]]
arch = "aarch64"
git-tree-sha1 = "77cfc0977c2006da2f89aac0de750229cf57600e"
julia_version = "1.10.0"
os = "macos"

    [[XDiag.download]]
    sha256 = "aad7e1e3e7eb2b3251d4ce27d29bf1f8c3b70d6b41a49d26485e37535f8d4722"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.aarch64-apple-darwin-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "aarch64"
git-tree-sha1 = "e12a3a74b5730c93ec32e90bf0755e94d735bbd8"
julia_version = "1.11.1"
os = "macos"

    [[XDiag.download]]
    sha256 = "8df9b1ae687e686872fe1632979c5b6c9c6e302cfd8019e06c50d35c7f75dac0"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.aarch64-apple-darwin-julia_version+1.11.1.tar.gz"
[[XDiag]]
arch = "aarch64"
git-tree-sha1 = "10a18115cc94f53aa792a29141f702eeb857ccf3"
julia_version = "1.12.0"
os = "macos"

    [[XDiag.download]]
    sha256 = "107f9c25f2ea4227ac08302a008f676b053e96a5874e426b751babeec5075872"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.aarch64-apple-darwin-julia_version+1.12.0.tar.gz"
[[XDiag]]
arch = "aarch64"
git-tree-sha1 = "d5ea020045300f7b41d458fb2c47632732ebf303"
julia_version = "1.13.0"
os = "macos"

    [[XDiag.download]]
    sha256 = "8d70d0d92a83a23a0b6930ed48a361f1aab48f9dca5b55a37b1a2fd46fa7d22d"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.aarch64-apple-darwin-julia_version+1.13.0.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2eb75466e3f2ad0afadd6d117f16e8a84cb3c908"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "334848ec9a6aa0c73237d3b5034f50391d7ed50f82a4fa371fa48cdfc25c82e0"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.aarch64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f89aee3b99137219f20e207da5fce2e98b6eb027"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "72c7bcdf29b97137a8dd6366af802fcd6cc3f8ef175480f10c299de1791e60a2"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.aarch64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "530b7bff75b9bdd225bc74dc7b68ba7160c2d684"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "ef2655ec1dd24461cda6377926e1c3e5f6f65cd283979d89ebb1bec082d91abb"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.aarch64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39aa1b4b34b903605f01df2a58377546a8a7fa16"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "85bf8c757c7386abae4b4731413d0c5007d64682f5b346c47736554a62feacfb"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.aarch64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5728596a509bbdf4cba309e74c38bd28706cbe6"
julia_version = "1.10.0"
libc = "musl"
os = "linux"

    [[XDiag.download]]
    sha256 = "de05f3addd924926a3f7e179e6d25ab8cad17c2bf0ec4cd4a4eed7430fdf65f5"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.aarch64-linux-musl-cxx11-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eef013c2b6367ffae89fb4042e4f4ec0c151e33a"
julia_version = "1.11.1"
libc = "musl"
os = "linux"

    [[XDiag.download]]
    sha256 = "ba64f42b7b1ce64d4b80cba4d8570267b98a4b7d3bfb9c90834bde9d16a064fd"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.aarch64-linux-musl-cxx11-julia_version+1.11.1.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78ec82d5c135af1b1a31e31cad86885c7fbe04d4"
julia_version = "1.12.0"
libc = "musl"
os = "linux"

    [[XDiag.download]]
    sha256 = "adb266804fd5aa7741348ce6e87dfa4e0bbd66300fdffdb947366a94de9a1bd4"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.aarch64-linux-musl-cxx11-julia_version+1.12.0.tar.gz"
[[XDiag]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed9eebf2a22927b500207c34e95e8bf122099509"
julia_version = "1.13.0"
libc = "musl"
os = "linux"

    [[XDiag.download]]
    sha256 = "4fd556fc6e5e7914787c27b6e84dff333522be7a613d10ee92df70e8cefa4c60"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.aarch64-linux-musl-cxx11-julia_version+1.13.0.tar.gz"
[[XDiag]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4dc88aa6e637322f79cb2e42b4aeb541ae9c734"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "2d3589ac46b518e7dbafb3634366acfdc48966663d50bef55aa4fdb35bfa413c"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.powerpc64le-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72fda94e10ed8af54d58916ef786f175d13ed242"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "46968a56f7e49b0c887f02b913421e9f2a908f94132704f6a44549c57a6536bc"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.powerpc64le-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[XDiag]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e90ecb21c15fad16690f417e70bbb88ee9ac1b9d"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "1b4dbbdae4db3f343d6858e20f04160744e7f68e12f55a5a401ce5eaf6525698"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.powerpc64le-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[XDiag]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca8d015c4b9ad44b66f3483b427ebd1a0e6073eb"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "c9dae971a8f4dd07f89a0741401fef9dd598b1052267ef04ecf51a8d1e27f70a"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.powerpc64le-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[XDiag]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "857a0cd223241d75b1bb9d776a9fd4ee19016cf1"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "229d017401864d9691756a37cb1a20222bc057731169e984cb4116507d7192ae"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.riscv64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[XDiag]]
arch = "x86_64"
git-tree-sha1 = "b87025be683990b65e23319dcc393fd5ebb924ac"
julia_version = "1.10.0"
os = "macos"

    [[XDiag.download]]
    sha256 = "e2220ed3ae701fb791aba42d36e2075e583532e457351203972010e794c5079e"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.x86_64-apple-darwin-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "x86_64"
git-tree-sha1 = "ef445dd8cfd4f36cee34853fd13c3844cf653046"
julia_version = "1.11.1"
os = "macos"

    [[XDiag.download]]
    sha256 = "efa6f0017d9e83a5025a732081af094eed703344e3156673785e2aac480c3445"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.x86_64-apple-darwin-julia_version+1.11.1.tar.gz"
[[XDiag]]
arch = "x86_64"
git-tree-sha1 = "483f2bf8d2f10afd1aa95fd5981e035be8853bd4"
julia_version = "1.12.0"
os = "macos"

    [[XDiag.download]]
    sha256 = "a87ba8c9cd1a93e5689d16d48278496afabaa96c6e65669e330d9af5cc03a3fe"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.x86_64-apple-darwin-julia_version+1.12.0.tar.gz"
[[XDiag]]
arch = "x86_64"
git-tree-sha1 = "da367f3706232306e44e5c1682dff5d21e3272c1"
julia_version = "1.13.0"
os = "macos"

    [[XDiag.download]]
    sha256 = "51cfc1dfe75b5b48279a15f78773ecd3bd24bffdce4fed7c54bcf3303a1627ba"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.x86_64-apple-darwin-julia_version+1.13.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8b975c9bb071db12a266851afbb3cfb21e480d3"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "f5e76de62859739a806a173ae811aca5bf78a02a9ddf94777bc3428bdefab23c"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6621dfbe60744d9e57211988f3a7a49548966381"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "f8063f186a252700940d00632e0ca85c8ff4d51d3107f2bf87e82cb80e2d185e"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.x86_64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b2fd6cb2a17eddab4e6fb4ab25ab1285a0cdd63"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "c4417d3baa900f4a5d581e6cf98c45eb79d126ad76bfe05a8cb07e7550b05ba9"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb6844a8c3ba65e8ccb3f6515d9e56efca96450e"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[XDiag.download]]
    sha256 = "1f5543323e1e6dd69e695b4fa5143e23d5f2b0432fd4b5cc4e97d5cca0218653"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.x86_64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d20dc8975fe4a713343ff8847e9dac57dd37d4a2"
julia_version = "1.10.0"
libc = "musl"
os = "linux"

    [[XDiag.download]]
    sha256 = "33fb3f6ac95f4d084351309ae23b8bdcb2117d42d7ad519ece714adc290b046b"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.x86_64-linux-musl-cxx11-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce89f98fde69792491efe2d82cd1aeddf12d25f5"
julia_version = "1.11.1"
libc = "musl"
os = "linux"

    [[XDiag.download]]
    sha256 = "5a1cc1f2b262c9398cbbc22216b369efd92411e34f019606f89250d477964d39"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.x86_64-linux-musl-cxx11-julia_version+1.11.1.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22e700274bf55b972b60bd0ccad2b917a95e0817"
julia_version = "1.12.0"
libc = "musl"
os = "linux"

    [[XDiag.download]]
    sha256 = "6d36e9366ba9076d2be12ec02b8e00c39ebae58bde61d5ff1d7939fe0ee4573b"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.x86_64-linux-musl-cxx11-julia_version+1.12.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ec5fb7558894af7b9d2545ba6aac6674b891113"
julia_version = "1.13.0"
libc = "musl"
os = "linux"

    [[XDiag.download]]
    sha256 = "d7d655c7e49a2a048f03188cf0f1ef4d8b6ec5ed9dc05cb07d96542c003128c0"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.x86_64-linux-musl-cxx11-julia_version+1.13.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "783aed3153133e3561adfe3bc7aa7ccaf98cb203"
julia_version = "1.10.0"
os = "windows"

    [[XDiag.download]]
    sha256 = "b22f736e4be5950671185ef2a2e3a065113eab1410a2d320bdfd3a1287260783"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1fbba59e6cc91f384cff5bcca14d6eabdf4b56b8"
julia_version = "1.11.1"
os = "windows"

    [[XDiag.download]]
    sha256 = "baabbfd569140f3bf49f255496b5d256f118e535b2c1ad8cafb019b6b90345d4"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.x86_64-w64-mingw32-cxx11-julia_version+1.11.1.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "760c88061cc499f96c315d4a816c7c702249b695"
julia_version = "1.12.0"
os = "windows"

    [[XDiag.download]]
    sha256 = "f9e7ca4ce49e0f92d06c315b2eda5adb38e1d4348f4c89393aa528261d649ad3"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
[[XDiag]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7a441e3bc5b103b123344236278398294773ef3"
julia_version = "1.13.0"
os = "windows"

    [[XDiag.download]]
    sha256 = "093782b0968ec07ef8dbb5d4891a33b92885d6b9114e742caf9885085747bebf"
    url = "https://github.com/JuliaBinaryWrappers/XDiag_jll.jl/releases/download/XDiag-v0.5.0+0/XDiag.v0.5.0.x86_64-w64-mingw32-cxx11-julia_version+1.13.0.tar.gz"
