# Autogenerated wrapper script for XDiag_jll for aarch64-apple-darwin-julia_version+1.7.0
export libxdiagjl

using libcxxwrap_julia_jll
using OpenBLAS_jll
using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("XDiag")
JLLWrappers.@declare_library_product(libxdiagjl, "@rpath/libxdiagjl.dylib")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll, OpenBLAS_jll, LLVMOpenMP_jll)
    JLLWrappers.@init_library_product(
        libxdiagjl,
        "lib/libxdiagjl.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
